name: py310mini
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - matplotlib
  - scikit-learn
  - numpy
  - tensorflow
  - keras
  - gensim
  - darts
  - ipykernel